# --------------------------------------------------
# HTTP -> HTTPS Yönlendirmesi (Tüm domainler)
# --------------------------------------------------
server {
    listen 80;
    server_name cagrivakti.com.tr www.cagrivakti.com.tr api.cagrivakti.com.tr;

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # WWW ise ana domaine yönlendir
    if ($host = www.cagrivakti.com.tr) {
        return 301 https://cagrivakti.com.tr$request_uri;
    }

    # Diğer tüm istekleri HTTPS'e yönlendir
    return 301 https://$host$request_uri;
}

# --------------------------------------------------
# WWW -> Ana Domain Yönlendirme (HTTPS)
# --------------------------------------------------
server {
    listen 443 ssl;
    server_name www.cagrivakti.com.tr;
    ssl_certificate /etc/letsencrypt/live/cagrivakti.com.tr/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cagrivakti.com.tr/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://cagrivakti.com.tr$request_uri;

}

# --------------------------------------------------
# Ana Domain (cagrivakti.com.tr) - HTTPS
# --------------------------------------------------
server {
    listen 443 ssl;
    server_name cagrivakti.com.tr;
    ssl_certificate /etc/letsencrypt/live/cagrivakti.com.tr/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cagrivakti.com.tr/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Proxy (Flask socket)
    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/cagrivakti/cagrivakti.sock;
    }

    # Statik Dosyalar
    location /static {
        alias /var/www/cagrivakti/app/static;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Vary "Accept-Encoding";
        access_log off;
    }

}

# --------------------------------------------------
# API Subdomain (api.cagrivakti.com.tr) - HTTPS
# --------------------------------------------------
server {
    listen 443 ssl;
    server_name api.cagrivakti.com.tr;

    ssl_certificate /etc/letsencrypt/live/api.cagrivakti.com.tr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.cagrivakti.com.tr/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/cagrivakti/cagrivakti.sock;
    }

    location /static {
        alias /var/www/cagrivakti/app/static;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Vary "Accept-Encoding";
        access_log off;
    }
}