"""StreamState tablosu eklendi

Revision ID: 027dbc534286
Revises: 7a1a82deb68f
Create Date: 2026-03-10 20:20:39.574767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027dbc534286'
down_revision = '7a1a82deb68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_state')
    # ### end Alembic commands ###
