"""Add utm_visits table

Revision ID: 1675203199f9
Revises: 78e9f40bb564
Create Date: 2026-06-27 19:22:07.046976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1675203199f9'
down_revision = '78e9f40bb564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utm_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utm_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utm_visits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_utm_visits_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_utm_visits_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_utm_visits_user_uid'), ['user_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_utm_visits_utm_campaign'), ['utm_campaign'], unique=False)
        batch_op.create_index(batch_op.f('ix_utm_visits_utm_medium'), ['utm_medium'], unique=False)
        batch_op.create_index(batch_op.f('ix_utm_visits_utm_source'), ['utm_source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utm_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utm_visits_utm_source'))
        batch_op.drop_index(batch_op.f('ix_utm_visits_utm_medium'))
        batch_op.drop_index(batch_op.f('ix_utm_visits_utm_campaign'))
        batch_op.drop_index(batch_op.f('ix_utm_visits_user_uid'))
        batch_op.drop_index(batch_op.f('ix_utm_visits_path'))
        batch_op.drop_index(batch_op.f('ix_utm_visits_ip_address'))
        batch_op.drop_index(batch_op.f('ix_utm_visits_created_at'))

    op.drop_table('utm_visits')
    # ### end Alembic commands ###
