"""AddGuideModel

Revision ID: 7419e9fe8d44
Revises: e1aa4a3d0063
Create Date: 2026-02-11 23:57:43.727538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7419e9fe8d44'
down_revision = 'e1aa4a3d0063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.create_index('idx_guide_active', ['is_active'], unique=False)
        batch_op.create_index('idx_guide_slug', ['slug'], unique=False)

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index('idx_contact_msg_read_date', ['is_read', 'created_at'], unique=False)

    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.create_index('idx_daily_content_query', ['category', 'is_active', 'last_shown'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_content_query')

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index('idx_contact_msg_read_date')

    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.drop_index('idx_guide_slug')
        batch_op.drop_index('idx_guide_active')

    op.drop_table('guide')
    # ### end Alembic commands ###
