"""Add extra indexes for performance

Revision ID: 78e9f40bb564
Revises: 027dbc534286
Create Date: 2026-05-14 22:54:09.244354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e9f40bb564'
down_revision = '027dbc534286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_redirect')
    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.create_index('idx_daily_content_type', ['content_type'], unique=False)
        batch_op.create_index('idx_daily_day_index', ['day_index'], unique=False)

    with op.batch_alter_table('ezan_vakti', schema=None) as batch_op:
        batch_op.create_index('idx_vakit_sehir', ['sehir'], unique=False)
        batch_op.create_index('idx_vakit_tarih', ['tarih'], unique=False)
        batch_op.create_index('idx_vakit_ulke', ['country_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ezan_vakti', schema=None) as batch_op:
        batch_op.drop_index('idx_vakit_ulke')
        batch_op.drop_index('idx_vakit_tarih')
        batch_op.drop_index('idx_vakit_sehir')

    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.drop_index('idx_daily_day_index')
        batch_op.drop_index('idx_daily_content_type')

    op.create_table('qr_redirect',
    sa.Column('id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('hit_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
