"""Add_Guide_model

Revision ID: 9dd0eed739c5
Revises: 7419e9fe8d44
Create Date: 2026-02-12 20:41:26.834113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd0eed739c5'
down_revision = '7419e9fe8d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.drop_index(batch_op.f('idx_guide_active'))
        batch_op.create_index('idx_guide_active_date', ['is_active', 'created_at'], unique=False)
        batch_op.drop_column('icon')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_index('idx_guide_active_date')
        batch_op.create_index(batch_op.f('idx_guide_active'), ['is_active'], unique=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
