"""Auto migration

Revision ID: e1aa4a3d0063
Revises: 
Create Date: 2026-02-07 20:21:03.652597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1aa4a3d0063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_shown', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_content', schema=None) as batch_op:
        batch_op.drop_column('last_shown')

    # ### end Alembic commands ###
